### ISSUE TITLE
Clematis flower - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#10]
# About
![Clematis Flower 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/0eee40aa-9cd6-4472-934d-7a6b10da4c06)
![Clematis flower 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/13d27372-92c1-4df1-93c7-47a14c3f738c)

Dimensions : refer to real life scale

# Assignee
* **Name: ** 
* **Email: ** 
* **Discord: Leah Chang** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Image



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/fb8f4c0f-a454-49fa-be2a-193979a3a10e)

**Comment by Bekreth** [comment]
The model that was submitted doesn't seem to open successfully on either mine, nor @AddieCornell machines.  Looking at it, the enormous size of the file (~300 MB) indicates that there may be a substantial amount of history associated to these object that wasn't clear out, or that the level of detail is prohibitively high (Possibly having already applied object smoothing). Can you verify that this file opens on your machine and that it is reasonably small? Additionally, can you update the file naming to match what was list in the onboarding file?
