### ISSUE TITLE
Foxglove flower - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#15]
# About
![Foxglove 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/b64b0740-27e4-4d74-9de7-56e6663f2727)
![Foxglove 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/db295b5e-416c-4db2-810f-630453d5152f)

Dimensions : refer to real life scale

# Assigned To
**Discord: Leah Chang** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Photo



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/82d13629-d4a4-483a-a3d9-4680fab23f21)
