### ISSUE TITLE
Lilly - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#17]
# About

![Lilly](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/a8d6b36b-699a-47be-9b59-5a04375fe3c8)

Dimensions : refer to real life scale 

# Assigned To
**Discord: Leah Chang** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Image


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/b1370de8-f545-400d-94a8-2aa69691f0ee)
