### ISSUE TITLE
Small Mirrors - 3D model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#20]
# About

![Mirror 03](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/6e77b8b4-3caf-4901-af79-a32fd608e55b)

**Model both the mirrors. 
Submit a maya file for each mirror. 
Object names : SmallMirror_01, SmallMirror_02**

Dimensions : width x depth x height
18 x 3 x 24

# Assigned To
**Discord: MeghanBrenay** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP image



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/b7ab8260-ae1a-4dcb-9e84-4cdec3df965b)
