### ISSUE TITLE
Night Shade Plant - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#21]
# About

![Night Shade 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/9d8f04a1-c4be-4bca-aa6b-8c381852e898)
![Night Shade 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/17a3b578-576a-464e-bfcd-e7f707456ae6)
![Night Shade 03](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/42932f78-ff72-4168-9cab-c31c6a226d9f)

Dimensions : refer to real life scale

# Assigned To
**Discord: Kay** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Images



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/648f002b-ba3a-4052-98ee-0126e3035afb)



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/6a66a7a5-0fee-40b1-a0c9-31565896e0c5)

**Comment by Bekreth** [comment]
Can you please make the following updates to this model:
1. Use the naming convention laid out in the submission file (e.g. HOA_XXXXX_GEO and HOA_XXXXX_GRP)
2. Clear history on all meshes
3. Center to model group on the world origin
4. Use the AI Standard material
5. Copy this model into the `BEN_Template_GEO.ma` file as it contains a common MacBeth reference
