### ISSUE TITLE
Peace Pin - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#26]
# About

![Peace pin](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/b883180a-61f0-4560-822b-a963f32dbce3)

Dimensions : width x depth x height 
1 x 0.2 x 1

# Assignee
* **Name: ** 
* **Email: ** 
* **Discord: ** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
I'll be starting this model tomorrow
