### ISSUE TITLE
Peonies flower - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#27]
# About

![Peonies 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/679e97d4-7e1c-4d4a-a3c1-76f35d13e168)
![Peonies](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/00937dda-e8c0-46b9-ab45-1c113719854e)

Dimensions : Refer to real life scale

# Assignee
* **Name: ** 
* **Email: ** 
* **Discord: ** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by AddieCornell** [comment]
assigned to Ryan
