### ISSUE TITLE
Picture Frame 02 - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#28]
# About
![Picture frame 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/e134dd09-e8c2-4fef-9500-33f5d4e07cee)
![Picture frame 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/66a50cf0-6ae4-4944-9815-016708fd37ae)

**Design Both Frames**

Dimensions : width x depth x height
6.5 x 1 x 7

# Assigned To 
**Discord: Sarah** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Checked in on this ticket, it hasn't been started yet as the [Drink Trolley](https://github.com/what-lights-us/fairy_play_collaborators/issues/14) has taken priority in modeling.  Will be started within the next day or two

**Comment by Bekreth** [comment]
Can you please make the following updaets:
1. Separate the two groups into independent Maya files
2. For Frame 1, one of the decor leaves isn't in it the group you made for it
3. Center the frames to the world origin
4. Clean up N-Gons and Triangles in the corner details


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/9739263e-c2db-48a4-95f6-723e35ceb355)
