### ISSUE TITLE
Pitcher Plant - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#29]
# About

![Pitcher plant 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/0501da79-ddc1-4792-8843-b784ed4873a7)

Dimensions : Refer to real life scale 

# Assigned To
**Discord: Ryan Hill** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Photo


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/2343913f-10da-49b1-ab01-657ba2aa2b5d)

**Comment by Bekreth** [comment]
Please make the following updates to this model
1. Use the proper naming for subgroups (e.g. HIL_XXXX_GRP)
2. Clear out the triangles and N-gons
3. Have all of your UVs fit within a single tile

![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/9953c8d6-a708-4b1b-8985-fa5c7bd40848)



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/7599ba9f-1350-4d73-a4a3-ddf546a3cb88)
