### ISSUE TITLE
Poison Ivy - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#30]
# About

![Poison Ivy 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/555fc6f8-2e5b-45c4-8950-c3749cc7f7d4)

Dimension - Refer to real life scale

# Assigned To
**Discord: Kay** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Images

![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/cb841f9a-07f3-4691-969b-13d736ddd009)



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/a9f163e7-5109-40b4-9c8b-37f7393ff187)

**Comment by Bekreth** [comment]
Can you please make the following updates:

1. Use the naming convention of HOA_XXXXX_GEO or HOA_XXXXX_GRP on the groups and models
2. Clear history on all meshes
3. Center the group to the world origin
4. Use the AI Standard material
5. Save your models into the a copied version of the `BEN_Template_GEO.ma` as it sets up a MacBeth chart in common with all files to having consistent lighting behavior
