### ISSUE TITLE
Rose Flower - 3D Model 

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#32]
# About

![Rose](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/6de45fed-6e55-4464-b0b7-18d0462ab731)

Dimensions : Refer to real life scale 
Note : Give us 2-3 Variations with the flower shape and count of leaves. 

# Assignee
* **Name: ** 
* **Email: ** 
* **Discord: ** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by AddieCornell** [comment]
assigned to sarah
