### ISSUE TITLE
Clock - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#38]
# About

![Clock 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/cecb17d3-6cc2-4763-a32d-bd1d5a3a66de)

Check with Avanthi Kamat about which one to model.

# Assignee
 ** ** 
**Email: ** 
**Discord: em willis** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Progress photos
![image-1.png](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/195048bd-2aec-4830-8880-f093992f466f)

**Comment by Bekreth** [comment]
This model is looking good, can you please make the following updates
1. Clean up all the triangles
2. Reorganize your UVs all fit on a single square without overlapping
3. Center the object at world origin


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/1c641aca-18fc-4a17-beb4-dd6ed68b2ba7)



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/821728e6-9440-4a3e-a139-db3dc0b73cf5)
