### ISSUE TITLE
Door Frame 02 - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#39]
# About

![Door Frame 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/8297a474-a86f-48e8-a638-2d53a2bc860d)

Dimensions : width x depth x height
8ft x 2ft x 10ft

# Assigned To

**Discord: Gabi O.** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Please make the following updates to your submission:
1. Remove lights and copy this model into the `BEN_Template_GEO.ma` file as it sets a consistent MacBeth reference chart
2. Remove triangles and N-gons
3. Set material to AI Standard
4. Update UV to not have overlapping shells
5. Aim to reduce polygons

![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/793ecef8-3220-4a1e-b75c-ddd7a3345a40)


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/c98d04a9-a267-4eaa-910d-1d6146be0624)
