### ISSUE TITLE
Dove Centrepiece - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#40]
# About

![Dove Sculpture](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/a91ae631-f01a-40cd-b046-7a297511b11a)

Requirement : Regular check-ins with Grace Martin and Avanthi Kamat

Dimensions : width x depth x height
84 x 84 x 96

# Assigned To
**Discord:**  MeghanBrenay

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Image



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/682a0a81-8fad-48eb-8d8d-4a117b57a7b8)
