### ISSUE TITLE
Wall Lanterns - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#42]
# About

![Lantern 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/3b9d6d60-a5d1-43a1-b617-8d0482b959bd)
![Lantern 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/48d1e196-3092-48ea-bc93-d50b5b996b3e)

**Model both Lanterns** 

Dimensions : width x depth x height
12 x 12 x 20

# Assigned To
**Discord: Avantika Chandrasekaran** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
This model is looking great. We'll need to do the following to call this complete
1. Rename all the GEOs inside of the GRP appropirately
2. Clear out the triangles that are inside the mesh


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/957d0197-2792-4981-a113-e33fabb29e25)
