### ISSUE TITLE
Candlestick Holder - 3D model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#45]
# About

![Candlestick Holder 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/ebc304c0-e049-4006-8fa9-c134ca8a60b7)

Dimensions : width x depth x height. (Dimensions do not include the candle)
4 x 4 x 8

# Assigned To
**Name:** 
**Discord: Midori Suzuki** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Image



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/0ef5b7a6-9a99-433b-ab03-1f8893e82705)

**Comment by Bekreth** [comment]
Please update the model as follows:
1. The size should be roughly 4in. x 4in. x 8in.
2. Update the file name to match what is specified in the reference document
3. Center the object on the world origin
4. Change the material to AI Standard
5. Update UVs to fit on a single tile without overlapping
6. Try to reduce poly count with fewer cylinder facets 

![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/dafc5e2e-d08d-4a58-96db-9faf1fcccce0)
