### ISSUE TITLE
Courtyard Fence - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#47]
# About

![Courtyard 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/1d908b27-78e7-447c-88cc-eabd61e88455)
![Courtyard 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/ca28be6d-3f59-4784-8ac1-7d2dbfda844c)

We need 2 Variations of this. One with the end pillars and one without. this would help us ensure a smooth repetition of the unit.

Dimensions (unit with the end pillars)  : width x depth x height
144 x 18 x 114

# Assigned To
**Name:** 
**Discord:** Monotosh 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Images



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/bbc4fd43-a31c-4905-8623-510de29b773a)




![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/f9043ec8-b1b6-41dc-8081-7dd20147defa)
