### ISSUE TITLE
Door Frame 01- 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#5]
# Door Frame
![Door Frame ](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/83e84dc9-623b-485d-ae32-5bd5d357e50d)

Dimensions : width x depth x height
8ft x 2ft x 10ft

# Assigned To

**Discord: Christopher Hughes** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
WIP Photo


![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/fe6e8e74-7e80-4b20-bf66-b23cc043b19b)
