### ISSUE TITLE
02 Flowers in a vase - 3D model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#58]
# Model all 5

 
![e429a22ee25021cb678dfc044692898e](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/ae1b88ab-99da-4725-a065-e1a9c74a83ef)

Dimensions : width x depth x height 
4 x 4 x 12  (~max)

Consider these dimensions as approximate measurements. The reference shows 5 different variations. So, use your artistic judgement to eyeball the height and thickness for each

# Assigned To
**Name:** 
**Discord:** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
With all the flowers that are being made for the garden, can we reuse those here and make this model just the value and a separate issue for combining the flowers and vases together?
