### ISSUE TITLE
Blood Lilly flower - 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#6]
Blood Lilly flower

![Blood lilly 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/8757e9b2-9ef0-43d0-b685-48ec58960e61)

Dimensions : Refer to real life 

# Assigned To
**Discord: Ryan Hill** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Could you please make the following updates
1. Remove the N-Gons
2. Reduce the number of polygons that your model uses
