### ISSUE TITLE
Chandelier 3D Model

### ISSUE THREAD

**Issue by avanthikamat** [what-lights-us/fairy_play_collaborators#9]
![Chandelier 01](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/1741b9c6-a835-48df-bfa9-8e01cd947249)
![Chandelier 02](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/d98f1786-12b5-4c4f-8cc2-2441554ed195)
![Chandelier 03](https://github.com/what-lights-us/fairy_play_collaborators/assets/164656962/541fec2f-e753-42ea-8bb1-6d80b8807c53)

**Choose any 2 designs you would like to model** 

Dimensions (width x height x depth)
30 x 30 x 50

# Assigned To

**Discord: em willis** 

# Definition of Done
* [ ] Lead who is acting as a point of contact has received the completed file and approved it for the project
* [ ] The completed files have been added to the appropriate location in the Git repo and have been merged to main

**Comment by Bekreth** [comment]
Progress photos
![image-2.png](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/94a0ed8f-3787-41ad-8da2-ada3efc917bc)

**Comment by Bekreth** [comment]
This model looks quite nice.  Please make the minor updates
1. Clear up the hidden triangles
2. Center the model on the world origin
3. Update the UV so the shells do not overlap



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/30227f95-2a4a-4733-85a9-c74d2e30627c)



![Image](https://github.com/what-lights-us/fairy_play_collaborators/assets/12821871/4130f4a6-1ce4-4439-b9a6-61f48573dfcc)
